"""remove_projects

Revision ID: cb6d044ff007
Revises: 0001
Create Date: 2026-06-13 14:26:59.528845
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb6d044ff007'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent: tablolar yoksa (taze kurulum) atlanir; varsa silinir.
    bind = op.get_bind()
    existing = set(sa.inspect(bind).get_table_names())
    for _t in ('project_chats', 'project_documents', 'projects'):
        if _t in existing:
            op.drop_table(_t)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('projects',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_chats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    # ### end Alembic commands ###
